### PR TITLE
Add systemd unit

### PR DESCRIPTION
**Pull request by swsnr**
Solves GH-1

### CODE REVIEW

**Comment by ntruessel** [comment]
Thanks!

**Comment by swsnr** [comment]
@ntruessel Thanks for merging.  Would you mind to update the AUR package as well?  I think the following change would suffice:

```diff
diff --git i/PKGBUILD w/PKGBUILD
index dd7647f..a1ee49b 100644
--- i/PKGBUILD
+++ w/PKGBUILD
@@ -1,6 +1,6 @@
 # Maintainer: Nicolas Trüssel <ntruessel@njsm.de>
 pkgname=mkinitcpio-bootmsg
-pkgver=0.1.0
+pkgver=0.2.0
 pkgrel=1
 pkgdesc="Mkinitcpio hook to display a message on boot"
 arch=(any)
@@ -11,12 +11,10 @@ makedepends=('git')
 backup=('etc/bootmsg.conf')
 install="$pkgname.install"
 source=("https://github.com/ntruessel/mkinitcpio-bootmsg/archive/v${pkgver}.tar.gz")
-sha256sums=('d29864b92800f9a60a721d89f486426195477dc9826fd3d9d9d235fe8ec5ef2e')
+sha256sums=('8e930c961d7ef27c7ea923e0665b58ef3782ab7b4f1e2aea2d24c92259d32fa4')
 
 package() {
 	cd "mkinitcpio-bootmsg-${pkgver}"
-	install -Dm644 bootmsg.conf "${pkgdir}/etc/bootmsg.conf"
-	install -Dm644 bootmsg.install "${pkgdir}/usr/lib/initcpio/install/bootmsg"
-	install -Dm644 bootmsg.hook "${pkgdir}/usr/lib/initcpio/hooks/bootmsg"
+	make DESTDIR="${pkgdir}" install
 	install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
 }
```

**Comment by ntruessel** [comment]
Already in progress. Currently testing the new version.

**Comment by ntruessel** [comment]
v0.2.0 is published in the AUR. :tada:

**Comment by swsnr** [comment]
Thanks a lot!

**Pull request merged**
